function registerImportObrigacoesRoutes(context) {
    const {
        app,
        axios,
        DRI_OBRIGACAO_ID,
        DMR_OBRIGACAO_ID,
        SAFT_OBRIGACAO_ID,
        IVA_OBRIGACAO_ID_MENSAL,
        IVA_OBRIGACAO_ID_TRIMESTRAL,
        M22_OBRIGACAO_ID,
        IES_OBRIGACAO_ID,
        M10_OBRIGACAO_ID,
        INVENTARIO_OBRIGACAO_ID,
        RELATORIO_UNICO_OBRIGACAO_ID,
        SUPABASE_URL,
        SUPABASE_KEY,
        SUPABASE_OBRIGACOES_MODELO,
        SUPABASE_CLIENTS_SOURCE,
        PORT,
        normalizeBoolean,
        normalizeIntValue,
        resolveMonthYear,
        nowIso,
        runGoffObrigacoesRobotDmrSs,
        runSaftObrigacoesRobotDri,
        fetchSupabaseTable,
        resolveObrigacaoModeloRow,
        pickFirstValue,
        normalizeIvaPeriodicidade,
        resolveObrigacaoPeriod,
        loadSupabaseCustomerLookup,
        findCustomerRowForObrigacao,
        resolveSupabaseCustomerIdFromLocalRow,
        loadLocalCollectedSets,
        loadSupabaseCollectedSourceIds,
        upsertLocalObrigacaoRecolha,
        syncRecolhaEstadoSupabase,
        updateObrigacaoPeriodoSupabase,
        markLocalObrigacaoRecolhaSynced,
        writeAuditLog,
        classifyDriCmpEnvStatus,
        classifyDmrProcessadoCertaStatus,
        classifySaftEnviadoStatus,
        classifyGoffSaftStatus,
        classifyGoffIvaStatus,
        classifyIvaProcessadoStatus,
        classifyM22ProcessadoStatus,
        classifyRelatorioUnicoStatus,
        normalizeDigits,
        parseDatePtToIso,
        parseIvaPeriodFromValue,
        normalizeLookupText,
        createIvaJobId,
        setIvaImportJob,
        ivaImportJobs,
        runSaftObrigacoesRobotDmr,
        runSaftObrigacoesRobotSaft,
        runGoffObrigacoesRobotSaft,
        runGoffObrigacoesRobotDmrAt,
        runGoffObrigacoesRobotIva,
        runGoffObrigacoesRobotM22,
        runGoffObrigacoesRobotIes,
        runGoffObrigacoesRobotM10,
        runGoffObrigacoesRobotInventario,
        runGoffObrigacoesRobotRelatorioUnico,
        runSaftObrigacoesRobotIva,
        runSaftObrigacoesRobotM22,
        runSaftObrigacoesRobotIes,
        runSaftObrigacoesRobotM10,
        runSaftObrigacoesRobotRelatorioUnico,
        materializeLocalCustomerFromSupabase,
    } = context;


    // ─── Sub-module delegation ───────────────────────────────────────
    const { registerObrigacoesCoreRoutes } = require('./obrigacoesCoreRoutes');
    const { registerObrigacoesAnnualIvaRoutes } = require('./obrigacoesAnnualIvaRoutes');

    registerObrigacoesCoreRoutes(context);
    registerObrigacoesAnnualIvaRoutes(context);
}

module.exports = {
    registerImportObrigacoesRoutes,
};
